version: '3.4'

services:
  webapi.customer:
    image: ${DOCKER_REGISTRY-}webapicustomer
    ports:
      - 7261:7261
    build:
      context: .
      dockerfile: WebApi.Customer\Dockerfile
    networks: 
      - database
    depends_on:
      - customerdb
    environment:
      - DB_HOST=customerdb
      - DB_NAME=project_myself
      - DB_SA_PASSWORD=Ad290399@

  webapi.product:
    image: ${DOCKER_REGISTRY-}webapiproduct
    ports:
      - 7207:7207
    build:
      context: .
      dockerfile: WebApi.Product\Dockerfile
    networks: 
      - database
    depends_on:
      - customerdb
    environment:
      - DB_HOST=customerdb
      - DB_NAME=project_myself
      - DB_SA_PASSWORD=Ad290399@

  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    ports:
      - 7040:7040
    build:
      context: .
      dockerfile: GatewayApi\Dockerfile


  blazorapp2:
    image: ${DOCKER_REGISTRY-}blazorapp2
    build:
      context: .
      dockerfile: BlazorApp2\Dockerfile
   
  customerdb:
    container_name: customer-db
    image: justin2004/mssql_server_tiny
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ad290399@
    networks:
      - database
    ports:
      - 8001:1433
networks:
  database: